--Creation du schema

CREATE TABLE FOURNISSEUR(
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  NOM VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USERS(
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  NOM VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE PRODUIT(
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  NOM VARCHAR(20) NOT NULL,
  PRIX_VENTE DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE PRODUIT_FOURNISSEUR(
  FK_FOURNISSEUR NUMBER,
  FK_PRODUIT NUMBER,
  PRIX_ACHAT DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (FK_FOURNISSEUR, FK_PRODUIT),
  FOREIGN KEY (FK_FOURNISSEUR) REFERENCES FOURNISSEUR(ID) ON DELETE CASCADE,
  FOREIGN KEY (FK_PRODUIT) REFERENCES PRODUIT(ID) ON DELETE CASCADE
);

CREATE TABLE COMMANDE(
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  FK_USER NUMBER,
  FOREIGN KEY (FK_USER) REFERENCES USERS(ID),
  PRIMARY KEY(ID)
);

CREATE TABLE COMMANDE_PRODUIT(
  FK_CMD NUMBER,
  FK_PRODUIT NUMBER,
  QTE NUMBER,
  FOREIGN KEY (FK_CMD) REFERENCES COMMANDE(ID),
  FOREIGN KEY (FK_PRODUIT) REFERENCES PRODUIT(ID),
  PRIMARY KEY (FK_CMD, FK_PRODUIT)
);

CREATE TABLE LIVRAISONS(
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  FK_CMD NUMBER,
  FOREIGN KEY (FK_CMD) REFERENCES COMMANDE(ID),
  PRIMARY KEY (ID)
);

CREATE TABLE LIVRAISONS_PRODUIT(
  FK_LIVRAISON NUMBER,
  FK_PRODUIT NUMBER,
  QTE NUMBER,
  LIVREE NUMBER(1),
  FOREIGN KEY (FK_LIVRAISON) REFERENCES LIVRAISONS(ID),
  FOREIGN KEY (FK_PRODUIT) REFERENCES PRODUIT(ID),
  PRIMARY KEY (FK_LIVRAISON, FK_PRODUIT)
);

--Insertion d un users
INSERT INTO USERS(NOM, PASSWORD) VALUES ('Mathieu', 'Password');
--Selection de l user
SELECT NOM, PASSWORD FROM USERS;

--Insertion de fournisseurs
INSERT INTO FOURNISSEUR(NOM) VALUES ('Rona');
INSERT INTO FOURNISSEUR(NOM) VALUES ('Rona Express');

Select * from fournisseur;

--Insertion de produits
INSERT INTO PRODUIT(NOM, PRIX_VENTE) VALUES ('Vis', 0.99);
INSERT INTO PRODUIT(NOM, PRIX_VENTE) VALUES ('Boulon', 1.99);

Select * from produit;

--Insertion de produit fournisseurs
INSERT INTO PRODUIT_FOURNISSEUR VALUES (1, 1, 0.19);
INSERT INTO PRODUIT_FOURNISSEUR VALUES (1, 2, 0.25);

INSERT INTO PRODUIT_FOURNISSEUR VALUES (1, 1, 0.24);

--Selection avec join pour obtenir le nom du produit, le nom du fournisseur, le prix d ahat et le prix de vente
Select produit.nom as nom_produit, fournisseur.nom as nom_fournisseur, prix_achat, prix_vente 
from produit_fournisseur
join produit on produit.id = produit_fournisseur.FK_produit
join fournisseur on fournisseur.id = produit_fournisseur.fk_fournisseur;

--Creation d une commande
INSERT INTO COMMANDE(FK_USER) VALUES (1);
Select * from commande;

--Insertion produit commandés
INSERT INTO COMMANDE_PRODUIT(FK_CMD, FK_PRODUIT, QTE) VALUES (1, 1, 5);
INSERT INTO COMMANDE_PRODUIT(FK_CMD, FK_PRODUIT, QTE) VALUES (1, 3, 10);

Select * from commande_produit;



--Selection du total par ligne commande
Select FK_CMD, PRODUIT.NOM, PRODUIT.PRIX_VENTE, qte, qte * prix_vente as total_ligne_commande 
  from commande_produit
  join produit on commande_produit.FK_PRODUIT = PRODUIT.ID;

--Selection du total de la commande  
Select SUM(total_ligne_commande) as total_commande from (
  Select FK_CMD, PRODUIT.NOM, PRODUIT.PRIX_VENTE, qte, qte * prix_vente as total_ligne_commande 
  from commande_produit
  join produit on commande_produit.FK_PRODUIT = PRODUIT.ID;
);

--Insertion de livraison
INSERT INTO LIVRAISONS (FK_CMD) VALUES (1);
INSERT INTO LIVRAISONS (FK_CMD) VALUES (1);

select * from livraisons;

--Insertion de boites pour la livraison
INSERT INTO LIVRAISONS_PRODUIT VALUES (1, 1, 5, 1);
INSERT INTO LIVRAISONS_PRODUIT VALUES (1, 2, 10, 0);

select * from livraisons_produit;

--Selection de la qte de produit commandé
Select sum(qte) from commande_produit where FK_CMD = 1;

--Selection de la qte de produit livres
Select sum(qte) as livre from livraisons 
  join livraisons_produit on livraisons_produit.FK_LIVRAISON = livraisons.ID
  where FK_CMD = 1 
  and livree = 1;

--Selection imbriquées pour le %age de produit livré
Select livre / commande * 100 as pourcent_livraison from 
  (Select sum(qte) as commande from livraisons_produit where fk_livraison = 1),
  (Select sum(qte) as livre from livraisons 
  join livraisons_produit on livraisons_produit.FK_LIVRAISON = livraisons.ID
  where FK_CMD = 1 
  and livree = 1);
