
  CREATE TABLE "CLIENTS"
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	"NAME" VARCHAR2(20 BYTE),
	"FIRSTNAME" VARCHAR2(20 BYTE),
	"PHONE" VARCHAR2(10 BYTE),
  PRIMARY KEY (ID)
   );

  CREATE TABLE "COMMANDE"
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	"CUSTOMER" NUMBER,
	"EMPLOYEE" NUMBER,
  PRIMARY KEY (ID)
   );

  CREATE TABLE "DEPARTEMENT"
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	"NAME" VARCHAR2(20 BYTE),
  PRIMARY KEY (ID)
   );

  CREATE TABLE "EMPLOYEE"
   (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	"NAME" VARCHAR2(20 BYTE),
	"FIRSTNAME" VARCHAR2(20 BYTE),
	"PHONE" VARCHAR2(10 BYTE),
	"DEPARTEMENT" NUMBER,
  PRIMARY KEY (ID),
  FOREIGN KEY (DEPARTEMENT) REFERENCES DEPARTEMENT(ID)
   );

   CREATE TABLE "PRODUCT"
    (	ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  "NAME" VARCHAR2(20 BYTE),
  "PRICE" NUMBER,
  "DEPARTEMENT" NUMBER,
  "SUPLIER" NUMBER,
   PRIMARY KEY (ID),
   FOREIGN KEY (SUPLIER) REFERENCES SUPLIER(ID)
 );


  CREATE TABLE "LIGNE_COMMANDE"
   (	"COMMANDE" NUMBER,
	"PRODUCT" NUMBER,
	"QTY" NUMBER,
  PRIMARY KEY (COMMANDE, PRODUCT),
  FOREIGN KEY (COMMANDE) REFERENCES COMMANDE(ID),
  FOREIGN KEY (PRODUCT) REFERENCES PRODUCT(ID)
  );

  CREATE TABLE "SUPLIER"
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	"NAME" VARCHAR2(20 BYTE)
  );
  
  -- Select toutes les lignes commandes de toutes les commandes des clients
  
  select clients.id as client_id,
    clients.name as client_name,
    employee.name as employee_name,
    clients.phone as client_phone,
    employee.phone as employee_phone,
    commande.id as command_id, employee as employee_id,
    ligne_commande.PRODUCT as produit_id,
    ligne_commande.qty,
    product.name as product_name,
    (product.PRICE * ligne_commande.qty) as price_line,
    departement.NAME as dep_name,
    suplier.NAME as sup_nam
    from clients
    join COMMANDE ON COMMANDE.ID = CLIENTS.ID
    join EMPLOYEE ON EMPLOYEE.ID = COMMANDE.EMPLOYEE
    join ligne_commande ON COMMANDE.ID = LIGNE_COMMANDE.COMMANDE
    join product on product.id = ligne_commande.PRODUCT
    join suplier on suplier.id = product.suplier
    join departement on departement.id = product.DEPARTEMENT
    
   
